version: "3.7"
services:
    composer:
        restart: 'no'
        image: 'composer'
        command: install
        volumes:
            - $PWD:/app
        depends_on:
            - phpfpm-apache

    phpfpm-apache:
        build:
            context: .
            dockerfile: php/Dockerfile
        #image: 'php:7.2-apache-stretch'
        ports:
            - '80:80'
        volumes:
            - $PWD:/var/www/html
            - $PWD/php/php.ini:/usr/local/etc/php/php.ini
            # - $PWD/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            # - $PWD/httpd/httpd.conf:/etc/apache2/sites-available/httpd.conf
        depends_on:
            - db

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        ports:
            - '8080:80'
        depends_on:
            - db

    db:
        image: 'mysql:5.7'
        ports:
            - '3306:3306'
        volumes:
            - $PWD/database:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=Codingisfun!
            - MYSQL_DATABASE=csm_inventory
