version: "3.3"
services:
    composer:
        restart: 'no'
        image: 'composer'
        command: install
        volumes:
            - $PWD:/app
        depends_on:
            - phpfpm-apache

    phpfpm-apache:
        build:
            context: .
            dockerfile: php/Dockerfile
        ports:
            - '80:80'
        volumes:
            - $PWD:/var/www/html
            - $PWD/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        ports:
            - '8080:80'
        depends_on:
            - db

    db:
        image: 'mysql:5.7.16'
        ports:
            - '3306:3306'
        volumes:
            - $PWD/database-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=Codingisfun!
            - MYSQL_DATABASE=csm_inventory
