csmit.staging:
  stage: staging
  configFile: ~/.ssh/config
  multiplexing: true
  deploy_path: /home/pi/sites/csmit.noahjahn.dev
  shared_files:
    - .env

csmit.production:
  stage: production
  branch: master
  configFile: ~/.ssh/config
  multiplexing: true
  deploy_path: /home/pi/sites/csmit.noahjahn.dev
  shared_files:
    - .env
