csmit.staging:
  stage: staging
  configFile: ~/.ssh/config
  multiplexing: true
  deploy_path: /var/www/html/csmit.noahjahn.dev
  shared_files:
    - .env

spark.csmit-inventory.production:
  stage: production
  # branch: master
  configFile: ~/.ssh/config
  multiplexing: true
  deploy_path: /var/www/html/inventory.csmgroup.com
  shared_files:
    - .env
